/* =============================== EVENTS COLLECTION =============================== */

//This file is to create and add sample event documents in the events collection

db.events.insertMany([
  {
    eventId: "event1",
    title: "Tech Conference 2026",
    description: "Annual technology conference",
    category: "Technology",
    dateTime: "2026-01-10, 10:00AM",
    venue: "Delhi",
    organizerId: "user1",
    price: 500,
    totalTickets: 200,
    availableTickets: 0,
    status: "completed"
  },
  {
    eventId: "event2",
    title: "Music Fest",
    description: "Live music concert",
    category: "Music",
    dateTime: "2026-04-05, 7:00PM",
    venue: "Mumbai",
    organizerId: "user8",
    price: 800,
    totalTickets: 300,
    availableTickets: 300,
    status: "upcoming"
  },
  {
    eventId: "event3",
    title: "Startup Meetup",
    description: "Entrepreneur networking event",
    category: "Business",
    dateTime: "2026-02-02, 11:00AM",
    venue: "Bangalore",
    organizerId: "user10",
    price: 300,
    totalTickets: 150,
    availableTickets: 100,
    status: "upcoming"
  },
  {
    eventId: "event4",
    title: "Art Exhibition",
    description: "Modern art display",
    category: "Art",
    dateTime: "2026-01-03, 09:00AM",
    venue: "Delhi",
    organizerId: "user11",
    price: 200,
    totalTickets: 100,
    availableTickets: 0,
    status: "completed"
  },
  {
    eventId: "event5",
    title: "Coding Workshop",
    description: "Hands-on coding session",
    category: "Education",
    dateTime: "2026-02-15, 10:00AM",
    venue: "Pune",
    organizerId: "user13",
    price: 400,
    totalTickets: 120,
    availableTickets: 90,
    status: "upcoming"
  },
  {
    eventId: "event6",
    title: "Dance Competition",
    description: "Inter-college dance competition",
    category: "Dance",
    dateTime: "2026-01-05, 4:00AM",
    venue: "Jaipur",
    organizerId: "user20",
    price: 250,
    totalTickets: 180,
    availableTickets: 0,
    status: "completed"
  },
  {
    eventId: "event7",
    title: "Food Carnival",
    description: "Street food festival",
    category: "Food",
    dateTime: "2026-04-12, 12:00PM",
    venue: "Amritsar",
    organizerId: "user10",
    price: 150,
    totalTickets: 250,
    availableTickets: 150,
    status: "upcoming"
  },
  {
    eventId: "event8",
    title: "Photography Workshop",
    description: "Basics of photography",
    category: "Photography",
    dateTime: "2026-02-25, 10:00AM",
    venue: "Chandigarh",
    organizerId: "user1",
    price: 350,
    totalTickets: 90,
    availableTickets: 90,
    status: "upcoming"
  },
  {
    eventId: "event9",
    title: "Yoga Camp",
    description: "Morning yoga sessions",
    category: "Health",
    dateTime: "2026-03-01, 06:00AM",
    venue: "Rishikesh",
    organizerId: "user11",
    price: 200,
    totalTickets: 80,
    availableTickets: 80,
    status: "upcoming"
  },
  {
    eventId: "event10",
    title: "Literature Fest",
    description: "Book readings and discussions",
    category: "Literature",
    dateTime: "2026-04-18, 11:00AM",
    venue: "Kolkata",
    organizerId: "user13",
    price: 300,
    totalTickets: 140,
    availableTickets: 100,
    status: "upcoming"
  },
  {
    eventId: "event11",
    title: "Film Screening",
    description: "Indie film showcase",
    category: "Film",
    dateTime: "2026-01-01, 18:00AM",
    venue: "Mumbai",
    organizerId: "user8",
    price: 250,
    totalTickets: 160,
    availableTickets: 0,
    status: "compeleted"
  },
  {
    eventId: "event12",
    title: "Robotics Expo",
    description: "Robotics and AI exhibition",
    category: "Technology",
    dateTime: "2026-05-01, 10:00AM",
    venue: "Hyderabad",
    organizerId: "user1",
    price: 600,
    totalTickets: 220,
    availableTickets: 220,
    status: "upcoming"
  },
  {
    eventId: "event13",
    title: "Career Fair",
    description: "Job and internship opportunities",
    category: "Career",
    dateTime: "2026-03-28, 10:00AM",
    venue: "Noida",
    organizerId: "user10",
    price: 100,
    totalTickets: 300,
    availableTickets: 300,
    status: "cancelled"
  },
  {
    eventId: "event14",
    title: "Fashion Show",
    description: "College fashion event",
    category: "Fashion",
    dateTime: "2026-04-02, 5:00PM",
    venue: "Delhi",
    organizerId: "user20",
    price: 700,
    totalTickets: 180,
    availableTickets: 180,
    status: "upcoming"
  },
  {
    eventId: "event15",
    title: "Science Exhibition",
    description: "Student science projects",
    category: "Science",
    dateTime: "2026-02-18, 10:00AM",
    venue: "Lucknow",
    organizerId: "user11",
    price: 150,
    totalTickets: 130,
    availableTickets: 80,
    status: "upcoming"
  },
  {
    eventId: "event16",
    title: "Gaming Tournament",
    description: "Competitive gaming event",
    category: "Gaming",
    dateTime: "2026-03-15, 6:00PM",
    venue: "Gurgaon",
    organizerId: "user13",
    price: 400,
    totalTickets: 200,
    availableTickets: 200,
    status: "cancelled"
  },
  {
    eventId: "event17",
    title: "Marathon",
    description: "City marathon event",
    category: "Sports",
    dateTime: "2026-04-10, 06:00AM",
    venue: "Delhi",
    organizerId: "user1",
    price: 300,
    totalTickets: 500,
    availableTickets: 500,
    status: "upcoming"
  },
  {
    eventId: "event18",
    title: "Drama Play",
    description: "Stage drama performance",
    category: "Drama",
    dateTime: "2026-03-08, 3:00PM",
    venue: "Bhopal",
    organizerId: "user8",
    price: 250,
    totalTickets: 110,
    availableTickets: 110,
    status: "cancelled"
  },
   {
    eventId: "event19",
    title: "AI Awareness Seminar",
    description: "Introduction to Artificial Intelligence for students",
    category: "Technology",
    dateTime: "2026-01-20, 11:00AM",
    venue: "Ahmedabad",
    organizerId: "user10",
    price: 200,
    totalTickets: 150,
    availableTickets: 0,
    status: "completed"
  },
  {
    eventId: "event20",
    title: "Cultural Night",
    description: "College cultural performances and music",
    category: "Cultural",
    dateTime: "2026-01-25, 6:30PM",
    venue: "Indore",
    organizerId: "user20",
    price: 300,
    totalTickets: 220,
    availableTickets: 0,
    status: "completed"
  }
]);